export const SpreadsheetData = [
    {
      id:"1",
      JobRequest: "Launch social media campaign for promotion",
      Submitted:"15-11-2024",
      Status: "In Progress",
      Submitter:"Aisha Patel",
      URL:"www.aishapatel23@gmail.com",
      Assigned:"Sophie Choudhary",
      Priority: "Medium",
      DueDate:"20-11-2024",
      Value:"6,200,000₹"
    },
    {
      id:"2",
    JobRequest: "Update press kit for company redesign",
    Submitted: "28-10-2024",
    Status: "Need to start",
    Submitter: "Irfan Khan",
    URL: "www.irfankhan.com",
    Assigned: "Tejas Pandey",
    Priority: "High",
    DueDate: "30-10-2024",
    Value: "3,500,000₹",
    },
    {
    id:"3",
    JobRequest: "Finalize user testing feedback for app",
    Submitted: "05-12-2024",
    Status: "In-process",
    Submitter: "Mark Johnson",
    URL: "www.markjohnson.com",
    Assigned: "Rachel Lee",
    Priority: "Medium",
    DueDate: "10-12-2024",
    Value: "4,750,000 ₹",  
    },
    {
    id:"4",
    JobRequest: "Design new features for the website",
    Submitted: "10-01-2025",
    Status: "Complete",
    Submitter: "Emily Green",
    URL: "www.emilygreen.com",
    Assigned: "Tom Wright",
    Priority: "Low",
    DueDate: "15-01-2025",
    Value: "5,900,000 ₹",
  },
  {
    id:"5",
    JobRequest: "Prepare financial report for Q4",
    Submitted: "25-01-2025",
    Status: "Blocked",
    Submitter: "Jessica Brown",
    URL: "www.jessicabrown.com",
    Assigned: "Kevin Smith",
    Priority: "Low",
    DueDate: "30-01-2025",
    Value: "2,800,000 ₹",
  }   
];
  